"use client";

import { ChangeEvent, FormEvent, useEffect, useRef, useState } from "react";
import { isSupabaseConfigured, supabase } from "@/lib/supabase";

type Tab = "discover" | "community" | "messages" | "profile";
type Language = "es" | "en";
type CommunityPost = { id: string | number; author: string; initial: string; time: string; text: string; video?: string; likes: number; commentsEnabled: boolean; comments: string[] };
type StoredPost = { id: string; caption: string | null; video_url: string | null; created_at: string; profiles: { display_name: string }[] | null };

const people = [
  { id: "sofia", name: "Sofía", age: 24, place: "Ciudad de México", emoji: "☕", accent: "from-orange-400 via-rose-500 to-violet-700", intro: "Una caminata, un café y una conversación sin prisa.", tags: ["Viajes", "Fotografía", "Café"], video: "https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4" },
  { id: "mila", name: "Mila", age: 26, place: "Barcelona", emoji: "🎨", accent: "from-fuchsia-600 via-purple-600 to-sky-700", intro: "Arte, mar y una playlist que cambia cada viernes.", tags: ["Arte", "Música", "Yoga"], video: "https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4" },
  { id: "camila", name: "Camila", age: 25, place: "Medellín", emoji: "🌿", accent: "from-emerald-500 via-teal-700 to-slate-900", intro: "Me gusta descubrir lugares nuevos y reír sin filtros.", tags: ["Senderismo", "Cine", "Comida"], video: "https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4" },
];

const copy = {
  es: { discover: "Descubrir", community: "Comunidad", messages: "Mensajes", profile: "Perfil", forYou: "Para ti", nearby: "Cerca", request: "Solicitar match", skip: "Siguiente", swipe: "Desliza hacia arriba para ver otro video", share: "Comparte más allá de las citas", publish: "Publicar", thought: "¿Qué estás pensando?", addVideo: "Agregar video", comments: "Comentarios", comment: "Comentar", send: "Enviar", public: "Público", private: "Privado", hidden: "Oculto", edit: "Editar", delete: "Borrar", settings: "Ajustes", logOut: "Cerrar sesión", gallery: "Galería", addMedia: "Agregar fotos o videos", matched: "¡Solicitud enviada!", profileReady: "Tu perfil", report: "Reportar", block: "Bloquear", hide: "Esconder", reply: "Responder", copy: "Copiar", disableComments: "Desactivar comentarios" },
  en: { discover: "Discover", community: "Community", messages: "Messages", profile: "Profile", forYou: "For you", nearby: "Nearby", request: "Request match", skip: "Next", swipe: "Swipe up for another video", share: "Share beyond dating", publish: "Publish", thought: "What are you thinking?", addVideo: "Add video", comments: "Comments", comment: "Comment", send: "Send", public: "Public", private: "Private", hidden: "Hidden", edit: "Edit", delete: "Delete", settings: "Settings", logOut: "Log out", gallery: "Gallery", addMedia: "Add photos or videos", matched: "Match request sent!", profileReady: "Your profile", report: "Report", block: "Block", hide: "Hide", reply: "Reply", copy: "Copy", disableComments: "Disable comments" },
};

export default function BlynkHome() {
  const [tab, setTab] = useState<Tab>("discover");
  const [language, setLanguage] = useState<Language>("es");
  const [personIndex, setPersonIndex] = useState(0);
  const [toast, setToast] = useState("");
  const [postText, setPostText] = useState("");
  const [posts, setPosts] = useState<CommunityPost[]>([{ id: 1, author: "Luis Hernandez", initial: "L", time: "Ahora", text: "Busco una conversación honesta. ¿Cuál es el mejor consejo que te han dado?", likes: 4, commentsEnabled: true, comments: ["Me encanta esa pregunta ✨"] }]);
  const [postVideo, setPostVideo] = useState("");
  const [postVideoFile, setPostVideoFile] = useState<File | null>(null);
  const [uploadingPost, setUploadingPost] = useState(false);
  const [comment, setComment] = useState("");
  const [menu, setMenu] = useState<string | number | null>(null);
  const [chat, setChat] = useState([{ from: "Sofía", text: "¡Hola! Me gustó tu video de presentación." }, { from: "me", text: "¡Gracias! El tuyo se ve increíble." }]);
  const [message, setMessage] = useState("");
  const [media, setMedia] = useState<string[]>([]);
  const [privacy, setPrivacy] = useState("Público");
  const startY = useRef(0);
  const t = copy[language];
  const person = people[personIndex];

  const notify = (value: string) => { setToast(value); window.setTimeout(() => setToast(""), 2600); };
  const nextPerson = () => setPersonIndex((value) => (value + 1) % people.length);
  const onTouchStart = (event: React.TouchEvent) => { startY.current = event.touches[0].clientY; };
  const onTouchEnd = (event: React.TouchEvent) => { if (startY.current - event.changedTouches[0].clientY > 55) nextPerson(); };
  const addPost = async () => {
    if ((!postText.trim() && !postVideo) || uploadingPost) return;
    let publishedVideo = postVideo;
    setUploadingPost(true);
    if (postVideoFile && isSupabaseConfigured && supabase) {
      const { data: { user }, error: userError } = await supabase.auth.getUser();
      if (userError || !user) { setUploadingPost(false); notify(language === "es" ? "Inicia sesión para publicar un video." : "Sign in to publish a video."); return; }
      const extension = postVideoFile.name.split(".").pop()?.toLowerCase() || "mp4";
      const path = `${user.id}/${crypto.randomUUID()}.${extension}`;
      const { error: uploadError } = await supabase.storage.from("blynk-media").upload(path, postVideoFile, { contentType: postVideoFile.type, upsert: false });
      if (uploadError) { setUploadingPost(false); notify(`${language === "es" ? "No se pudo subir el video" : "Video upload failed"}: ${uploadError.message}`); return; }
      publishedVideo = supabase.storage.from("blynk-media").getPublicUrl(path).data.publicUrl;
      const { error: profileError } = await supabase.from("profiles").upsert({ id: user.id, display_name: user.user_metadata.display_name || user.email?.split("@")[0] || "Blynk user" });
      if (profileError) { setUploadingPost(false); notify(`${language === "es" ? "No se pudo preparar tu perfil" : "Could not prepare your profile"}: ${profileError.message}`); return; }
      const { error: postError } = await supabase.from("posts").insert({ user_id: user.id, caption: postText.trim() || null, video_url: publishedVideo });
      if (postError) { setUploadingPost(false); notify(`${language === "es" ? "Video subido, pero no se pudo guardar la publicación" : "Video uploaded, but the post could not be saved"}: ${postError.message}`); return; }
    }
    setPosts((items) => [{ id: Date.now(), author: "Luis Hernandez", initial: "L", time: "Ahora", text: postText.trim(), video: publishedVideo || undefined, likes: 0, commentsEnabled: true, comments: [] }, ...items]);
    setPostText(""); setPostVideo(""); setPostVideoFile(null); setUploadingPost(false);
    notify(language === "es" ? "Publicación compartida" : "Post shared");
  };
  const addComment = (postId: string | number) => { if (!comment.trim()) return; setPosts((items) => items.map((post) => post.id === postId ? { ...post, comments: [...post.comments, comment.trim()] } : post)); setComment(""); };
  const uploadMedia = (event: ChangeEvent<HTMLInputElement>) => { const files = Array.from(event.target.files ?? []); setMedia((current) => [...current, ...files.slice(0, Math.max(0, 6 - current.length)).map((file) => URL.createObjectURL(file))]); };
  const selectPostVideo = (event: ChangeEvent<HTMLInputElement>) => { const file = event.target.files?.[0]; if (file) { setPostVideoFile(file); setPostVideo(URL.createObjectURL(file)); } };
  const sendMessage = (event: FormEvent) => { event.preventDefault(); if (!message.trim()) return; setChat((items) => [...items, { from: "me", text: message.trim() }]); setMessage(""); };

  useEffect(() => { const onKey = (event: KeyboardEvent) => { if (event.key === "ArrowDown") nextPerson(); }; window.addEventListener("keydown", onKey); return () => window.removeEventListener("keydown", onKey); }, []);
  useEffect(() => {
    if (!isSupabaseConfigured || !supabase) return;
    const client = supabase;
    async function loadCommunity() {
      const { data, error } = await client.from("posts").select("id, caption, video_url, created_at, profiles(display_name)").order("created_at", { ascending: false }).limit(30);
      if (error || !data?.length) return;
      setPosts((data as unknown as StoredPost[]).map((post) => { const displayName = post.profiles?.[0]?.display_name || "Blynk user"; return { id: post.id, author: displayName, initial: displayName.slice(0, 1).toUpperCase(), time: new Intl.DateTimeFormat(language === "es" ? "es-MX" : "en-US", { dateStyle: "medium" }).format(new Date(post.created_at)), text: post.caption || "", video: post.video_url || undefined, likes: 0, commentsEnabled: true, comments: [] }; }));
    }
    void loadCommunity();
  }, [language]);

  return <main className="blynk-shell min-h-screen">
    <header className="sticky top-0 z-30 border-b border-white/10 bg-[#090914e8] backdrop-blur-xl"><div className="relative mx-auto flex max-w-6xl items-center justify-between px-4 py-3 sm:px-6"><button onClick={() => setTab("discover")} className="flex items-center gap-2 text-xl font-black tracking-tight"><span aria-hidden="true" className="drop-shadow-[0_0_8px_#f13ab5]"><svg viewBox="0 0 96 58" className="h-7 w-9"><defs><linearGradient id="blynk-mini-eye" x1="0" x2="1"><stop stopColor="#ff4fac"/><stop offset="1" stopColor="#a855f7"/></linearGradient></defs><path d="M3 29C16 11 31 3 48 3s32 8 45 26C80 47 65 55 48 55S16 47 3 29Z" fill="url(#blynk-mini-eye)"/><path d="M13 29C24 18 35 13 48 13s24 5 35 16C72 40 61 45 48 45S24 40 13 29Z" fill="#fff4fb"/><circle cx="48" cy="29" r="11" fill="#18bfc9"/><circle cx="48" cy="29" r="6" fill="#07101e"/><circle cx="44" cy="25" r="2.5" fill="white"/></svg></span><span className="bg-gradient-to-r from-pink-400 to-violet-400 bg-clip-text text-transparent">Blynk</span></button><span aria-label="Ojo Blynk" className="absolute left-1/2 top-1/2 -translate-x-1/2 -translate-y-1/2 drop-shadow-[0_0_14px_#f13ab5]"><svg viewBox="0 0 96 58" className="h-10 w-16 sm:h-12 sm:w-20" role="img"><defs><linearGradient id="blynk-eye" x1="0" x2="1"><stop stopColor="#ff4fac"/><stop offset="1" stopColor="#a855f7"/></linearGradient><radialGradient id="blynk-iris"><stop stopColor="#d8ffff"/><stop offset=".42" stopColor="#46e4e2"/><stop offset=".72" stopColor="#117f9c"/><stop offset="1" stopColor="#071726"/></radialGradient></defs><path d="M3 29C16 11 31 3 48 3s32 8 45 26C80 47 65 55 48 55S16 47 3 29Z" fill="url(#blynk-eye)"/><path d="M10 29C21 16 34 10 48 10s27 6 38 19C75 42 62 48 48 48S21 42 10 29Z" fill="#fff4fb"/><circle cx="48" cy="29" r="16" fill="url(#blynk-iris)"/><circle cx="48" cy="29" r="8" fill="#07101e"/><circle cx="42" cy="23" r="4" fill="white"/><circle cx="54" cy="35" r="2" fill="#baffff"/></svg></span><div className="flex items-center gap-2"><select aria-label="Idioma" value={language} onChange={(event) => setLanguage(event.target.value as Language)} className="rounded-full border border-white/10 bg-white/5 px-3 py-2 text-sm text-white outline-none"><option value="es">ES</option><option value="en">EN</option></select><a href="/login" className="hidden rounded-full border border-white/15 px-4 py-2 text-sm font-bold text-white sm:block">{language === "es" ? "Ingresar" : "Sign in"}</a></div></div></header>
    <div className="mx-auto grid max-w-6xl grid-cols-1 gap-6 px-4 pb-24 pt-6 md:px-6 lg:grid-cols-[185px_minmax(0,1fr)_260px]">
      <aside className="hidden lg:block"><nav className="blynk-card sticky top-24 space-y-1 rounded-3xl p-2">{([ ["discover", "▷"], ["community", "◎"], ["messages", "✉"], ["profile", "◌"] ] as [Tab, string][]).map(([key, icon]) => <button key={key} onClick={() => setTab(key)} className={`flex w-full items-center gap-3 rounded-2xl px-4 py-3 text-left text-sm font-bold ${tab === key ? "bg-white/10 text-pink-300" : "text-white/55 hover:bg-white/5 hover:text-white"}`}><span>{icon}</span>{t[key]}</button>)}</nav></aside>
      <section className="min-w-0">
        {tab === "discover" && <div className="mx-auto max-w-md" onTouchStart={onTouchStart} onTouchEnd={onTouchEnd}><div className="mb-4 grid grid-cols-2 rounded-2xl bg-white/5 p-1 text-center text-sm font-bold"><button className="rounded-xl bg-white/10 py-3 text-pink-300">{t.forYou}</button><button className="py-3 text-white/45">{t.nearby}</button></div><article className="blynk-card relative aspect-[9/14] overflow-hidden rounded-[2rem]" aria-label={`${person.name}, ${person.age}`}><div className={`absolute inset-0 bg-gradient-to-br ${person.accent}`} /><video key={person.id} className="absolute inset-0 size-full object-cover opacity-55 mix-blend-overlay" src={person.video} autoPlay muted loop playsInline /><div className="video-shade absolute inset-0" /><div className="absolute left-4 right-4 top-4 flex items-center justify-between"><span className="rounded-full border border-white/15 bg-black/30 px-3 py-1.5 text-xs font-semibold backdrop-blur">● {person.place}</span><span className="rounded-full bg-black/30 px-3 py-1.5 text-xs backdrop-blur">00:18</span></div><button onClick={() => notify(language === "es" ? "Perfil guardado" : "Profile saved")} className="soft-button absolute right-4 top-16 grid size-11 place-items-center rounded-full border border-white/15 bg-black/30 text-lg backdrop-blur" aria-label="Guardar">♡</button><div className="absolute inset-x-0 bottom-0 p-6"><span className="mb-3 inline-flex rounded-full bg-emerald-400/20 px-3 py-1 text-xs font-bold text-emerald-100">● ONLINE</span><h1 className="text-3xl font-black">{person.name}, {person.age}</h1><p className="mt-2 text-sm leading-6 text-white/85">{person.intro}</p><div className="mt-4 flex flex-wrap gap-2">{person.tags.map((tag) => <span key={tag} className="rounded-full border border-white/15 bg-black/20 px-3 py-1 text-xs font-semibold">{tag}</span>)}</div></div></article><p className="animate-pulse py-3 text-center text-xs text-white/45">↑ {t.swipe}</p><div className="grid grid-cols-[1fr_1.45fr] gap-3"><button onClick={nextPerson} className="soft-button rounded-2xl border border-white/15 bg-white/5 py-4 font-bold text-white/80">× {t.skip}</button><button onClick={() => { notify(t.matched); nextPerson(); }} className="soft-button pink-gradient rounded-2xl py-4 font-bold shadow-[0_12px_28px_#ef38b755]">♥ {t.request}</button></div></div>}
        {tab === "community" && <div className="mx-auto max-w-xl space-y-4">
          <div><p className="text-sm font-semibold text-pink-300">Blynk Community</p><h1 className="mt-1 text-2xl font-black">{t.share}</h1></div>
          <div className="blynk-card rounded-3xl p-4">
            <textarea value={postText} onChange={(event) => setPostText(event.target.value)} placeholder={t.thought} className="min-h-24 w-full resize-none bg-transparent text-sm text-white outline-none placeholder:text-white/35" />
            {postVideo && <div className="relative mt-3 overflow-hidden rounded-2xl border border-white/10"><video src={postVideo} className="max-h-72 w-full bg-black object-contain" controls muted playsInline /><button onClick={() => { setPostVideo(""); setPostVideoFile(null); }} className="absolute right-2 top-2 rounded-full bg-black/70 px-3 py-1 text-xs font-bold">× Quitar</button></div>}
            <div className="mt-3 flex items-center justify-between border-t border-white/10 pt-3"><label className="cursor-pointer text-sm font-bold text-white/60">▣ {t.addVideo}<input onChange={selectPostVideo} className="hidden" type="file" accept="video/*" /></label><button disabled={uploadingPost} onClick={addPost} className="soft-button pink-gradient rounded-xl px-5 py-2.5 text-sm font-bold disabled:cursor-wait disabled:opacity-60">{uploadingPost ? (language === "es" ? "Subiendo…" : "Uploading…") : t.publish}</button></div>
          </div>
          {posts.map((post) => <article key={post.id} className="blynk-card rounded-3xl p-5">
            <div className="flex items-center gap-3"><span className="grid size-10 place-items-center rounded-full bg-gradient-to-br from-pink-400 to-violet-600 font-black">{post.initial}</span><div><p className="font-bold">{post.author}</p><p className="text-xs text-white/45">{post.time} · {t.public}</p></div><button onClick={() => setMenu(menu === post.id ? null : post.id)} className="ml-auto rounded-full p-2 text-white/50 hover:bg-white/10">•••</button></div>
            {menu === post.id && <div className="mt-3 grid grid-cols-2 gap-2 rounded-2xl border border-white/10 bg-black/30 p-2 text-xs"><button onClick={() => setPosts((items) => items.map((item) => item.id === post.id ? { ...item, commentsEnabled: !item.commentsEnabled } : item))}>{t.disableComments}</button><button onClick={() => notify(t.report)}>{t.report}</button><button onClick={() => notify(t.block)}>{t.block}</button><button onClick={() => setPosts((items) => items.filter((item) => item.id !== post.id))}>{t.delete}</button></div>}
            {post.text && <p className="mt-4 leading-6 text-white/90">{post.text}</p>}{post.video && <video src={post.video} className="mt-4 w-full rounded-2xl bg-black" controls autoPlay muted loop playsInline />}
            <div className="mt-4 flex gap-5 border-t border-white/10 pt-3 text-sm text-white/55"><button onClick={() => setPosts((items) => items.map((item) => item.id === post.id ? { ...item, likes: item.likes + 1 } : item))}>♡ {post.likes}</button><span>◌ {post.comments.length} {t.comments.toLowerCase()}</span></div>
            {post.commentsEnabled && <div className="mt-3 space-y-2">{post.comments.map((entry, index) => <button onClick={() => notify(`${t.reply} · ${t.copy} · ${t.hide}`)} className="block w-full rounded-xl bg-white/5 p-3 text-left text-sm text-white/75" key={`${entry}-${index}`}>{entry}</button>)}<div className="flex gap-2"><input value={comment} onChange={(event) => setComment(event.target.value)} className="min-w-0 flex-1 rounded-xl border border-white/10 bg-black/20 px-3 py-2 text-sm outline-none" placeholder={t.comment} /><button onClick={() => addComment(post.id)} className="rounded-xl bg-white/10 px-3 text-sm font-bold">{t.send}</button></div></div>}
          </article>)}
        </div>}
        {tab === "messages" && <div className="mx-auto flex h-[68dvh] max-w-xl flex-col overflow-hidden rounded-3xl blynk-card"><div className="flex items-center gap-3 border-b border-white/10 p-4"><span className="grid size-10 place-items-center rounded-full bg-gradient-to-br from-orange-400 to-pink-500">S</span><div><p className="font-bold">Sofía</p><p className="text-xs text-emerald-300">● online</p></div><button className="ml-auto text-white/55">⌕</button></div><div className="no-scrollbar flex-1 space-y-3 overflow-y-auto p-4">{chat.map((item, index) => <p key={index} className={`max-w-[78%] rounded-2xl px-4 py-3 text-sm ${item.from === "me" ? "pink-gradient ml-auto" : "bg-white/10"}`}>{item.text}</p>)}</div><form onSubmit={sendMessage} className="flex gap-2 border-t border-white/10 p-3"><input value={message} onChange={(event) => setMessage(event.target.value)} placeholder={language === "es" ? "Escribe un mensaje…" : "Write a message…"} className="min-w-0 flex-1 rounded-full bg-white/5 px-4 py-3 text-sm outline-none" /><button className="pink-gradient rounded-full px-5 font-bold">➤</button></form></div>}
        {tab === "profile" && <div className="mx-auto max-w-xl space-y-4"><section className="blynk-card overflow-hidden rounded-3xl"><div className="h-28 bg-gradient-to-r from-pink-500 via-fuchsia-600 to-violet-700" /><div className="px-5 pb-5"><div className="-mt-12 flex items-end justify-between"><span className="grid size-24 place-items-center rounded-3xl border-4 border-[#151525] bg-gradient-to-br from-amber-300 to-rose-500 text-3xl font-black">L</span><button onClick={() => notify(t.edit)} className="rounded-xl border border-white/15 px-4 py-2 text-sm font-bold">✎ {t.edit}</button></div><h1 className="mt-3 text-2xl font-black">Luis Hernandez</h1><p className="text-sm text-white/60">Los Angeles · 26 · Español, English</p><p className="mt-3 text-sm leading-6 text-white/80">Diseñando una vida que se sienta auténtica. Me gustan las conversaciones que empiezan sin presión.</p><div className="mt-4 flex gap-5 text-sm"><span><b>12</b> publicaciones</span><span><b>48</b> matches</span><span><b>1.2k</b> vistas</span></div></div></section><section className="blynk-card rounded-3xl p-5"><div className="flex items-center justify-between"><h2 className="font-black">{t.gallery}</h2><label className="soft-button cursor-pointer rounded-xl bg-white/10 px-3 py-2 text-xs font-bold">+ {t.addMedia}<input onChange={uploadMedia} className="hidden" multiple type="file" accept="image/*,video/*" /></label></div><div className="mt-4 grid grid-cols-3 gap-2">{media.map((source) => <div key={source} role="img" aria-label="Contenido del perfil" className="aspect-square rounded-xl bg-cover bg-center" style={{ backgroundImage: `url(${source})` }} />)}{media.length === 0 && <p className="col-span-3 rounded-2xl border border-dashed border-white/15 p-7 text-center text-sm text-white/45">{language === "es" ? "Añade hasta 6 fotos o videos para completar tu perfil." : "Add up to 6 photos or videos to complete your profile."}</p>}</div></section><section className="blynk-card rounded-3xl p-5"><div className="flex items-center justify-between"><h2 className="font-black">{t.settings}</h2><select value={privacy} onChange={(event) => setPrivacy(event.target.value)} className="rounded-xl border border-white/10 bg-black/20 px-3 py-2 text-sm"><option>{t.public}</option><option>{t.private}</option><option>{t.hidden}</option></select></div><button onClick={() => notify(language === "es" ? "Sesión cerrada en este prototipo" : "Signed out in this prototype")} className="mt-4 text-sm font-bold text-rose-300">↪ {t.logOut}</button></section></div>}
      </section>
      <aside className="hidden lg:block"><div className="blynk-card sticky top-24 rounded-3xl p-5"><p className="text-xs font-bold uppercase tracking-widest text-pink-300">Blynk Pro</p><h2 className="mt-2 text-lg font-black">Tu perfil está al 78%</h2><p className="mt-2 text-sm leading-5 text-white/55">Agrega un video de presentación y recibe más conexiones relevantes.</p><button onClick={() => setTab("profile")} className="soft-button mt-4 w-full rounded-xl bg-white/10 py-3 text-sm font-bold">{t.profileReady}</button></div></aside>
    </div>
    <nav className="mobile-safe fixed inset-x-0 bottom-0 z-30 flex justify-around border-t border-white/10 bg-[#0b0b17ef] px-3 py-2 backdrop-blur-xl lg:hidden">{([ ["discover", "▷"], ["community", "◎"], ["messages", "✉"], ["profile", "◌"] ] as [Tab, string][]).map(([key, icon]) => <button key={key} onClick={() => setTab(key)} className={`grid place-items-center gap-1 px-2 py-1 text-[10px] font-bold ${tab === key ? "text-pink-300" : "text-white/45"}`}><span className="text-xl">{icon}</span>{t[key]}</button>)}</nav>
    {toast && <div className="fixed bottom-20 left-1/2 z-50 -translate-x-1/2 rounded-full bg-white px-5 py-3 text-sm font-bold text-[#171322] shadow-xl lg:bottom-8">{toast}</div>}
  </main>;
}
