"use client";

import Link from "next/link";
import { FormEvent, useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { supabase } from "@/lib/supabase";

export default function ResetPasswordPage() {
  const router = useRouter(); const [password, setPassword] = useState(""); const [confirmPassword, setConfirmPassword] = useState(""); const [ready, setReady] = useState(false); const [notice, setNotice] = useState(""); const [busy, setBusy] = useState(false);
  useEffect(() => { if (!supabase) return; const client = supabase; const check = async () => { const { data: { session } } = await client.auth.getSession(); setReady(Boolean(session)); if (!session) setNotice("Open this page using the secure link sent to your email."); }; void check(); }, []);
  const save = async (event: FormEvent) => { event.preventDefault(); if (!supabase || !ready) return; if (password.length < 8) { setNotice("Use at least 8 characters."); return; } if (password !== confirmPassword) { setNotice("Passwords do not match."); return; } setBusy(true); const { error } = await supabase.auth.updateUser({ password }); setBusy(false); if (error) { setNotice(error.message); return; } setNotice("Password updated. Redirecting to Blynk…"); window.setTimeout(() => router.replace("/"), 1000); };
  return <main className="blynk-shell grid min-h-screen place-items-center px-4 py-10"><form onSubmit={save} className="blynk-card w-full max-w-md rounded-[2rem] p-7"><Link href="/login" className="text-sm font-bold text-pink-300">← Back to sign in</Link><p className="mt-7 text-xs font-bold uppercase tracking-widest text-pink-300">Blynk account help</p><h1 className="mt-2 text-3xl font-black">Choose a new password</h1><p className="mt-3 text-sm leading-6 text-white/60">Use a new password with at least 8 characters.</p><label className="mt-6 block text-sm font-bold">New password<input disabled={!ready} required minLength={8} autoComplete="new-password" type="password" value={password} onChange={(event) => setPassword(event.target.value)} className="mt-2 w-full rounded-xl border border-white/15 bg-black/20 px-4 py-3 text-white outline-none disabled:opacity-50" /></label><label className="mt-4 block text-sm font-bold">Confirm password<input disabled={!ready} required minLength={8} autoComplete="new-password" type="password" value={confirmPassword} onChange={(event) => setConfirmPassword(event.target.value)} className="mt-2 w-full rounded-xl border border-white/15 bg-black/20 px-4 py-3 text-white outline-none disabled:opacity-50" /></label><button disabled={!ready || busy} className="pink-gradient soft-button mt-6 w-full rounded-xl py-3.5 font-bold disabled:opacity-60">{busy ? "Updating…" : "Update password"}</button>{notice && <p role="status" className="mt-4 rounded-xl border border-white/10 bg-white/5 p-3 text-sm leading-6 text-white/75">{notice}</p>}</form></main>;
}
